# Generated by Django 5.1.6 on 2025-02-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='media/movie/images/'),
        ),
    ]
